#!/usr/bin/python
#-*- coding:utf-8 -*-
 
from PyQt5 import QtCore, QtGui, QtWidgets
 
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 540)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        
        self.label1 = QtWidgets.QLabel(self.centralWidget)       
        self.label1.setGeometry(QtCore.QRect(70, 62, 54, 12))
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(self.centralWidget)
        self.label2.setGeometry(QtCore.QRect(70, 102, 54, 12))
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(self.centralWidget)
        self.label3.setGeometry(QtCore.QRect(70, 142, 54, 12))
        self.label3.setObjectName("label3")
        self.label4 = QtWidgets.QLabel(self.centralWidget)
        self.label4.setGeometry(QtCore.QRect(70, 182, 54, 12))
        self.label4.setObjectName("label4")
        self.label5 = QtWidgets.QLabel(self.centralWidget)
        self.label5.setGeometry(QtCore.QRect(70, 222, 54, 12))
        self.label5.setObjectName("label5")
        self.LineEdit1 = QtWidgets.QLineEdit(self.centralWidget)
        self.LineEdit1.setGeometry(QtCore.QRect(110, 60, 113, 20))
        self.LineEdit1.setObjectName("LineEdit1")
        self.LineEdit2 = QtWidgets.QLineEdit(self.centralWidget)
        self.LineEdit2.setGeometry(QtCore.QRect(110, 100, 113, 20))
        self.LineEdit2.setObjectName("LineEdit2")
        self.ComboBox1 = QtWidgets.QComboBox(self.centralWidget)
        self.ComboBox1.setGeometry(QtCore.QRect(110, 140, 87, 22))
        self.ComboBox1.setObjectName("ComboBox1")
        self.ComboBox1.addItem("诗部")
        self.ComboBox1.addItem("词部")
        self.ComboBox1.addItem("曲部")
        self.ComboBox2 = QtWidgets.QComboBox(self.centralWidget)
        self.ComboBox2.setGeometry(QtCore.QRect(110, 180, 87, 22))
        self.ComboBox2.setObjectName("ComboBox2")
        self.ComboBox2.addItem("一等奖")
        self.ComboBox2.addItem("二等奖")
        self.ComboBox2.addItem("三等奖")
        self.ComboBox2.addItem("优秀奖")
        self.TextEdit1=QtWidgets.QTextEdit(self.centralWidget)
        self.TextEdit1.setGeometry(QtCore.QRect(110, 220, 211, 171))
        self.TextEdit1.setObjectName("TextEdit1")      
        self.PushButton1 = QtWidgets.QPushButton(self.centralWidget)
        self.PushButton1.setGeometry(QtCore.QRect(110, 430, 75, 40))
        self.PushButton1.setObjectName("PushButton1")        
        self.PushButton2 = QtWidgets.QPushButton(self.centralWidget)
        self.PushButton2.setGeometry(QtCore.QRect(380, 60, 75, 40))
        self.PushButton2.setObjectName("PushButton2")
        self.PushButton3 = QtWidgets.QPushButton(self.centralWidget)
        self.PushButton3.setGeometry(QtCore.QRect(480, 60, 90, 40))
        self.PushButton3.setObjectName("PushButton3")
        self.TextEdit2 = QtWidgets.QTextEdit(self.centralWidget)
        self.TextEdit2.setGeometry(QtCore.QRect(380, 120, 320, 271))
        self.TextEdit2.setObjectName("TextEdit2")
        self.TextEdit2.setReadOnly(True)
        
        MainWindow.setCentralWidget(self.centralWidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "奖状一键生成"))
        self.label1.setText(_translate("MainWindow", "作者:"))
        self.label2.setText(_translate("MainWindow", "题目:"))
        self.label3.setText(_translate("MainWindow", "类别:"))
        self.label4.setText(_translate("MainWindow", "奖项:"))
        self.label5.setText(_translate("MainWindow", "内容:"))
        self.PushButton1.setText(_translate("MainWindow", "生成奖状"))
        self.PushButton2.setText(_translate("MainWindow", "导入文件"))
        self.PushButton3.setText(_translate("MainWindow", "生成全部奖状"))